server:
  port: 8092

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      inventory-sucess: inventory-sucess
      inventory-fail: inventory-fail
    consumer:
      group-id: inventory-group
      auto-offset-reset: latest

  logging:
    level:
      org:
        apache:
          kafka: OFF

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:invetory-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostreSQLDialect